"""empty message

Revision ID: 03293a771a07
Revises: a76b65ba9914
Create Date: 2024-07-18 17:30:49.515652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03293a771a07'
down_revision = 'a76b65ba9914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forecast_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecast_request_city_id'), ['city_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecast_request_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecast_request_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecast_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecast_request_user_id'))
        batch_op.drop_index(batch_op.f('ix_forecast_request_timestamp'))
        batch_op.drop_index(batch_op.f('ix_forecast_request_city_id'))

    op.drop_table('forecast_request')
    # ### end Alembic commands ###
